# Generated by Django 3.2.23 on 2023-11-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('usetime', models.DurationField(blank=True, null=True)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
