# Generated by Django 3.2.23 on 2023-11-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0002_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Suresubject',
        ),
    ]
