# Generated by Django 3.2.23 on 2023-11-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0004_auto_20231107_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suresubject',
            name='name',
            field=models.CharField(max_length=30, verbose_name='対象名'),
        ),
        migrations.CreateModel(
            name='Calsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='受付開始時間')),
                ('tail_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='受付終了時間')),
                ('display_period', models.PositiveSmallIntegerField(verbose_name='表示期間')),
                ('Step', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='刻み幅')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonCal.suresubject', verbose_name='予約対象')),
            ],
        ),
    ]
