# Generated by Django 3.2.23 on 2023-11-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0007_alter_calsetting_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calsetting',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonCal.suresubject', unique=True, verbose_name='予約対象'),
        ),
    ]
