# Generated by Django 3.2.23 on 2023-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0009_auto_20231108_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='終了時Y間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frame',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='コマ数'),
        ),
    ]
