# Generated by Django 3.2.23 on 2023-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0010_auto_20231108_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=31, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='終了時間'),
        ),
    ]
