# Generated by Django 3.2.23 on 2023-11-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0012_schedule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calsetting',
            name='subject_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MonCal.suresubject', verbose_name='予約対象'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=31, null=True, verbose_name='使用目的'),
        ),
    ]
