# Generated by Django 3.2.23 on 2023-11-08 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MonCal', '0015_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
    ]
