# Generated by Django 3.2.23 on 2023-11-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0016_alter_event_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
    ]
