# Generated by Django 3.2.23 on 2023-11-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0017_remove_event_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
