# Generated by Django 3.2.23 on 2023-11-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0019_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
