# Generated by Django 3.2.23 on 2023-11-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0023_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(to='MonCal.Person', verbose_name='メンバー'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=31, null=True, verbose_name='名前'),
        ),
    ]
