# Generated by Django 3.2.23 on 2023-11-08 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MonCal', '0024_auto_20231108_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
    ]
