# Generated by Django 3.2.23 on 2023-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0026_schedule_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='member',
            field=models.ManyToManyField(to='MonCal.Person', verbose_name='メンバー'),
        ),
    ]
