# Generated by Django 3.2.23 on 2023-11-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0027_schedule_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
    ]
