# Generated by Django 3.2.23 on 2023-11-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0028_remove_schedule_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
