# Generated by Django 3.2.23 on 2023-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0029_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='suresubject',
            name='Step',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='刻み幅（分）'),
        ),
        migrations.AddField(
            model_name='suresubject',
            name='display_period',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='表示期間'),
        ),
        migrations.AddField(
            model_name='suresubject',
            name='head_time',
            field=models.TimeField(null=True, verbose_name='受付開始時間'),
        ),
        migrations.AddField(
            model_name='suresubject',
            name='tail_time',
            field=models.TimeField(null=True, verbose_name='受付終了時間'),
        ),
    ]
