# Generated by Django 3.2.23 on 2023-11-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0030_auto_20231109_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calsetting',
        ),
    ]
