# Generated by Django 3.2.23 on 2023-11-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0033_rename_about_schedule_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Detail',
            new_name='detail',
        ),
    ]
