# Generated by Django 3.2.23 on 2023-11-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0034_rename_detail_schedule_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
