# Generated by Django 3.2.23 on 2023-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0035_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
    ]
