# Generated by Django 3.2.23 on 2023-11-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0037_auto_20231110_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='starttime',
        ),
    ]
