# Generated by Django 3.2.23 on 2023-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0038_auto_20231110_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='endtime',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='starttime',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
    ]
