# Generated by Django 3.2.23 on 2023-11-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0039_auto_20231110_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=31, null=True, verbose_name='タイトル'),
        ),
    ]
