# Generated by Django 3.2.23 on 2023-11-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0040_alter_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to='MonCal.Person', verbose_name='メンバー'),
        ),
    ]
