# Generated by Django 3.2.23 on 2023-11-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0044_auto_20231116_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
