# Generated by Django 3.2.23 on 2023-11-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0045_auto_20231116_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(null=True, verbose_name='刻み幅')),
                ('unit', models.CharField(blank=True, max_length=8, null=True, verbose_name='単位')),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.schedule', verbose_name='スケジュール')),
            ],
        ),
        migrations.CreateModel(
            name='Excludeday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.cycle', verbose_name='サイクル')),
            ],
        ),
    ]
