# Generated by Django 3.2.23 on 2023-11-17 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MonCal', '0046_cycle_excludeday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to='MonCal.Person', verbose_name='メンバー'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
