# Generated by Django 3.2.23 on 2023-11-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0047_auto_20231117_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='frame',
        ),
    ]
