# Generated by Django 3.2.23 on 2023-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0052_remove_schedule_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cycle',
            field=models.CharField(default='nocycle', max_length=15, verbose_name='繰り返し'),
        ),
    ]
