# Generated by Django 3.2.23 on 2023-11-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0054_auto_20231121_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='member',
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.suresubject', verbose_name='利用設備'),
        ),
    ]
