# Generated by Django 3.2.23 on 2023-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0055_auto_20231121_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cycle',
            field=models.CharField(default='nocycle', max_length=15, verbose_name='繰り返し'),
        ),
    ]
