# Generated by Django 3.2.23 on 2023-11-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0057_suresubject_subjectclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='cycle',
        ),
    ]
