# Generated by Django 3.2.23 on 2023-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0058_remove_eventschedule_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventschedule',
            old_name='Event',
            new_name='event',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='cycle',
            field=models.CharField(default='nocycle', max_length=15, verbose_name='繰り返し'),
        ),
    ]
