# Generated by Django 3.2.23 on 2023-11-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0060_alter_eventschedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='subschedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.schedule', verbose_name='設備スケジュール'),
        ),
    ]
