# Generated by Django 3.2.23 on 2023-11-22 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0061_eventschedule_subschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='head_time',
            field=models.TimeField(default=datetime.time(8, 30), verbose_name='受付開始時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tail_time',
            field=models.TimeField(default=datetime.time(17, 30), verbose_name='受付終了時間'),
        ),
    ]
