# Generated by Django 3.2.23 on 2023-11-22 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0062_auto_20231122_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suresubject',
            name='head_time',
            field=models.TimeField(default=datetime.time(8, 30), verbose_name='受付開始時間'),
        ),
        migrations.AlterField(
            model_name='suresubject',
            name='tail_time',
            field=models.TimeField(default=datetime.time(17, 30), verbose_name='受付終了時間'),
        ),
    ]
