# Generated by Django 3.2.23 on 2023-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0063_auto_20231122_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='all', max_length=31, verbose_name='行事場所'),
        ),
    ]
