# Generated by Django 3.2.23 on 2023-11-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0064_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subschedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.eventschedule', verbose_name='行事スケジュール'),
        ),
    ]
