# Generated by Django 3.2.23 on 2023-11-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0065_schedule_subschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='subject_pk',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='利用設備'),
        ),
    ]
