# Generated by Django 3.2.23 on 2023-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0066_auto_20231123_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='subject_pk',
            field=models.CharField(blank=True, default='0', max_length=15, verbose_name='利用設備'),
        ),
    ]
