# Generated by Django 3.2.23 on 2023-11-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0068_alter_eventschedule_subject_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='weekday',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
