# Generated by Django 3.2.23 on 2023-11-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0069_auto_20231124_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='区分名')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.subject_type', verbose_name='設備区分'),
        ),
        migrations.AddField(
            model_name='suresubject',
            name='subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MonCal.subject_type', verbose_name='設備区分'),
        ),
    ]
