# Generated by Django 3.2.23 on 2023-11-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0071_auto_20231124_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='時間名')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='時刻')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='head_time',
            field=models.TimeField(default='08:30:00', verbose_name='受付開始時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tail_time',
            field=models.TimeField(default='17:30:00', verbose_name='受付終了時間'),
        ),
        migrations.AlterField(
            model_name='suresubject',
            name='head_time',
            field=models.TimeField(default='08:30:00', verbose_name='受付開始時間'),
        ),
        migrations.AlterField(
            model_name='suresubject',
            name='tail_time',
            field=models.TimeField(default='17:30:00', verbose_name='受付終了時間'),
        ),
    ]
