# Generated by Django 3.2.23 on 2023-11-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0072_auto_20231124_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='head_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tail_time',
        ),
        migrations.RemoveField(
            model_name='suresubject',
            name='head_time',
        ),
        migrations.RemoveField(
            model_name='suresubject',
            name='tail_time',
        ),
    ]
