# Generated by Django 3.2.23 on 2023-11-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0074_working_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Working_days',
            new_name='Working_day',
        ),
    ]
