# Generated by Django 3.2.23 on 2023-11-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0075_rename_working_days_working_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suresubject',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='suresubject',
            name='subject_type',
            field=models.ManyToManyField(blank=True, null=True, to='MonCal.Subject_type', verbose_name='設備区分'),
        ),
    ]
