# Generated by Django 3.2.23 on 2023-11-29 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0077_alter_suresubject_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suresubject',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='suresubject',
            name='subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonCal.subject_type', verbose_name='設備区分'),
        ),
    ]
