# Generated by Django 3.2.23 on 2023-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0078_auto_20231129_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='event',
            name='subject_type',
            field=models.ManyToManyField(to='MonCal.Subject_type', verbose_name='設備区分'),
        ),
    ]
