# Generated by Django 3.2.23 on 2023-11-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0079_auto_20231129_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='subject_pk',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='subject_pk',
            field=models.ManyToManyField(to='MonCal.Suresubject', verbose_name='利用設備'),
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='subschedule',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='subschedule',
            field=models.ManyToManyField(to='MonCal.Schedule', verbose_name='設備スケジュール'),
        ),
    ]
