# Generated by Django 3.2.23 on 2023-11-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0080_auto_20231129_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suresubject',
            name='subjectclass',
        ),
    ]
