# Generated by Django 3.2.23 on 2023-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0082_auto_20231129_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='event',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='place',
            field=models.ManyToManyField(to='MonCal.Event', verbose_name='場所'),
        ),
    ]
