# Generated by Django 3.2.23 on 2023-11-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0084_auto_20231129_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='subject',
        ),
    ]
