# Generated by Django 3.2.23 on 2023-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0085_remove_eventschedule_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31, verbose_name='コード')),
                ('name', models.CharField(max_length=31, verbose_name='名前')),
            ],
        ),
    ]
