# Generated by Django 3.2.23 on 2023-11-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0088_schedule_cycle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='cycle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MonCal.cycle_type', verbose_name='繰り返し区分'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cycle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MonCal.cycle_type', verbose_name='繰り返し区分'),
        ),
    ]
