# Generated by Django 3.2.23 on 2023-11-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0089_auto_20231130_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='cycle',
        ),
    ]
