# Generated by Django 3.2.23 on 2023-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0090_auto_20231130_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='subschedule',
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='room',
            field=models.ManyToManyField(blank=True, to='MonCal.Suresubject', verbose_name='設備'),
        ),
    ]
