# Generated by Django 3.2.23 on 2023-12-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0092_alter_eventschedule_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subschedule',
        ),
    ]
