# Generated by Django 3.2.23 on 2023-12-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0094_cycle_pause_pause_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='cycle_stopday',
            field=models.DateField(blank=True, null=True, verbose_name='繰り返し停止日'),
        ),
        migrations.AlterField(
            model_name='cycle_pause',
            name='pause_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MonCal.pause_type', verbose_name='定期的な予定の削除'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
