# Generated by Django 3.2.23 on 2023-12-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0095_auto_20231204_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='cycle_stopday',
        ),
    ]
