# Generated by Django 3.2.23 on 2023-12-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0096_remove_eventschedule_cycle_stopday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cycle_type',
        ),
    ]
