# Generated by Django 3.2.23 on 2023-12-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0099_auto_20231215_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonCal.event', verbose_name='場所'),
        ),
    ]
