# Generated by Django 3.2.23 on 2023-12-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0100_alter_room_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='room',
            field=models.ManyToManyField(blank=True, to='MonCal.Room', verbose_name='部屋'),
        ),
    ]
