# Generated by Django 3.2.23 on 2023-12-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0101_alter_eventschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='room',
            field=models.ManyToManyField(blank=True, to='MonCal.Suresubject', verbose_name='設備'),
        ),
    ]
