# Generated by Django 3.2.23 on 2023-12-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0102_alter_eventschedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='room',
        ),
    ]
