# Generated by Django 3.2.23 on 2023-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0103_remove_eventschedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='room',
            field=models.ManyToManyField(blank=True, to='MonCal.Room', verbose_name='設備'),
        ),
    ]
