# Generated by Django 3.2.23 on 2023-12-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonCal', '0106_parson'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='swap_mode',
            field=models.BooleanField(default=False, verbose_name='縦横切り替え'),
        ),
    ]
